import { auth, db, COLLECTIONS } from './firebase.js';
import { onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { collection, getDocs, addDoc, deleteDoc, doc, updateDoc } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let editing={};
function section(id){ $$('.admin-section').forEach(s=>s.classList.remove('active')); $('#'+id).classList.add('active'); $$('.admin-nav button').forEach(b=>b.classList.toggle('active',b.dataset.section===id)); }
$$('[data-section]').forEach(b=>b.onclick=()=>section(b.dataset.section));
$('#logout').onclick=()=>signOut(auth).then(()=>location.href='index.html');
onAuthStateChanged(auth,u=>{ if(!u){location.href='index.html'} else init(); });
async function docs(name){ const s=await getDocs(collection(db,name)); return s.docs.map(d=>({id:d.id,...d.data()})); }
async function renderProducts(){ const arr=await docs(COLLECTIONS.products); $('#productList').innerHTML=arr.map(x=>`<div class="row"><b>${x.title||x.name}</b><button class="edit" data-editp="${x.id}">Редактировать</button><button class="danger" data-delp="${x.id}">Удалить</button></div>`).join('')||'<p class="muted">Пока пусто</p>'; document.querySelectorAll('[data-delp]').forEach(b=>b.onclick=async()=>{await deleteDoc(doc(db,COLLECTIONS.products,b.dataset.delp));renderProducts();}); document.querySelectorAll('[data-editp]').forEach(b=>b.onclick=async()=>{const item=arr.find(x=>x.id===b.dataset.editp); editing.product=item.id; $('#pTitle').value=item.title||''; $('#pPrice').value=item.price||''; $('#pCategory').value=item.category||''; $('#pImage').value=item.image||''; $('#pDesc').value=item.description||'';}); }
async function renderCats(){ const arr=await docs(COLLECTIONS.categories); $('#catList').innerHTML=arr.map(x=>`<div class="row"><b>${x.title||x.name}</b><button class="edit" data-editc="${x.id}">Редактировать</button><button class="danger" data-delc="${x.id}">Удалить</button></div>`).join('')||'<p class="muted">Пока пусто</p>'; document.querySelectorAll('[data-delc]').forEach(b=>b.onclick=async()=>{await deleteDoc(doc(db,COLLECTIONS.categories,b.dataset.delc));renderCats();}); document.querySelectorAll('[data-editc]').forEach(b=>b.onclick=()=>{const item=arr.find(x=>x.id===b.dataset.editc); editing.cat=item.id; $('#cTitle').value=item.title||'';}); }
async function renderBanners(){ const arr=await docs(COLLECTIONS.banners); $('#bannerList').innerHTML=arr.map(x=>`<div class="row"><b>${x.title}</b><button class="edit" data-editb="${x.id}">Редактировать</button><button class="danger" data-delb="${x.id}">Удалить</button></div>`).join('')||'<p class="muted">Пока пусто</p>'; document.querySelectorAll('[data-delb]').forEach(b=>b.onclick=async()=>{await deleteDoc(doc(db,COLLECTIONS.banners,b.dataset.delb));renderBanners();}); document.querySelectorAll('[data-editb]').forEach(b=>b.onclick=()=>{const item=arr.find(x=>x.id===b.dataset.editb); editing.banner=item.id; $('#bTitle').value=item.title||''; $('#bText').value=item.text||''; $('#bImage').value=item.image||'';}); }
function init(){renderProducts();renderCats();renderBanners();}
$('#productForm').onsubmit=async e=>{e.preventDefault(); const data={title:$('#pTitle').value,price:Number($('#pPrice').value),category:$('#pCategory').value,image:$('#pImage').value,description:$('#pDesc').value,createdAt:new Date().toISOString()}; if(editing.product){await updateDoc(doc(db,COLLECTIONS.products,editing.product),data); editing.product=null;}else await addDoc(collection(db,COLLECTIONS.products),data); e.target.reset(); renderProducts();};
$('#catForm').onsubmit=async e=>{e.preventDefault(); const data={title:$('#cTitle').value}; if(editing.cat){await updateDoc(doc(db,COLLECTIONS.categories,editing.cat),data); editing.cat=null;}else await addDoc(collection(db,COLLECTIONS.categories),data); e.target.reset(); renderCats();};
$('#bannerForm').onsubmit=async e=>{e.preventDefault(); const data={title:$('#bTitle').value,text:$('#bText').value,image:$('#bImage').value,createdAt:new Date().toISOString()}; if(editing.banner){await updateDoc(doc(db,COLLECTIONS.banners,editing.banner),data); editing.banner=null;}else await addDoc(collection(db,COLLECTIONS.banners),data); e.target.reset(); renderBanners();};
