import { auth, db } from './firebase.js';
import { onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { collection, addDoc, getDocs, deleteDoc, doc, getDoc, serverTimestamp, query, orderBy } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
const $=s=>document.querySelector(s); let active='products';
const schemas={products:['title','price','oldPrice','category','image','rating'],categories:['title'],banners:['title','subtitle','text','image']};
function formHtml(type){return `<h2>${type==='products'?'Товары':type==='categories'?'Категории':'Баннеры'}</h2><form id="adminForm" class="admin-grid">${schemas[type].map(f=>`<label class="field">${f}<input id="${f}" ${f==='price'||f==='oldPrice'?'type="number"':''}></label>`).join('')}<button class="primary">Добавить</button></form><div id="list"></div>`}
async function load(type=active){ active=type; document.querySelectorAll('.admin-side button').forEach(b=>b.classList.toggle('active',b.dataset.type===type)); $('#panel').innerHTML=formHtml(type); $('#adminForm').onsubmit=save; const snap=await getDocs(query(collection(db,type), orderBy('createdAt','desc'))).catch(()=>null); const items=snap?snap.docs.map(d=>({id:d.id,...d.data()})):[]; $('#list').innerHTML=items.map(x=>`<div class="list-item"><div><b>${x.title||x.name}</b><p class="muted">${x.category||x.subtitle||x.text||''}</p></div><button class="danger" onclick="removeItem('${type}','${x.id}')">Удалить</button></div>`).join('')||'<p class="muted">Пока пусто</p>'}
async function save(e){e.preventDefault(); const data={createdAt:serverTimestamp()}; schemas[active].forEach(f=>data[f]=$('#'+f).value); await addDoc(collection(db,active),data); load(active)}
window.removeItem=async(t,id)=>{await deleteDoc(doc(db,t,id));load(t)}; window.load=load;
onAuthStateChanged(auth, async user=>{ if(!user){location.href='login.html';return} const snap=await getDoc(doc(db,'users',user.uid)); if(!snap.exists() || snap.data().role!=='admin'){ $('#panel').innerHTML='<h2>Нет доступа</h2><p>Для админки нужен role: admin в Firestore → users → ваш UID.</p>'; return;} $('#adminEmail').textContent=user.email; load('products')});
window.logout=()=>signOut(auth).then(()=>location.href='index.html');
