
import { auth, db, COLLECTIONS } from './firebase.js';
import { onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut, sendEmailVerification } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { collection, getDocs, setDoc, doc, getDoc } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);let cart=JSON.parse(localStorage.getItem('cart')||'[]');let favs=JSON.parse(localStorage.getItem('favorites')||'[]');let allProducts=[];
const money=v=>`${Number(v||0).toLocaleString('ru-RU')} ₽`;const stock=p=>Number(p.stock??p.quantity??p.count??1);const title=p=>p.title||p.name||'Без названия';const img=p=>p.image||p.imageUrl||p.photo||'';const group=p=>p.group||p.category||p.categoryName||'Без группы';
function oldPrice(p){return Number(p.oldPrice||p.priceOld||p.compareAtPrice||0)}function discount(p){const d=Number(p.discount||p.discountPercent||0);if(d>0)return d;const op=oldPrice(p), pr=Number(p.price||0);return op>pr&&pr>0?Math.round((op-pr)/op*100):0}
function saveCart(){localStorage.setItem('cart',JSON.stringify(cart));$('#cartCount')&&($('#cartCount').textContent=cart.length)}function saveFav(){localStorage.setItem('favorites',JSON.stringify(favs))}
async function loadCollection(name){const snap=await getDocs(collection(db,name));return snap.docs.map(d=>({id:d.id,...d.data()}))}
function isHome(p,section){const hs=String(p.homeSection||p.homeBlock||'').toLowerCase();const tag=String(p.tag||'').toLowerCase();if(section==='new')return p.showOnHome===true&&(hs==='new'||tag==='new');if(section==='bestsellers')return p.showOnHome===true&&(hs==='bestsellers'||hs==='best'||tag==='best'||tag==='bestseller');if(section==='hot')return p.showOnHome===true&&(!hs||hs==='hot'||tag==='hot'||!tag);return false}
function card(p){const d=discount(p), op=oldPrice(p), inst=(p.installment||p.installmentAvailable);return `<article class="product-card"><button class="fav-btn ${favs.includes(p.id)?'active':''}" data-fav="${p.id}" type="button">♡</button><a class="product-card-link" href="product.html?id=${p.id}"><div class="product-img">${d?`<span class="discount-badge">-${d}%</span>`:''}${img(p)?`<img src="${img(p)}" alt="${title(p)}">`:'Фото'}</div><div class="product-title">${title(p)}</div><div class="product-group">${group(p)}</div>${inst?`<div class="installment-badge">Доступно в рассрочку</div>`:''}<div class="price-row-card"><div class="price-current price">${money(p.price)}</div>${op?`<div class="old-price price-old">${money(op)}</div>`:''}</div></a><button class="cart" data-cart="${p.id}" type="button">В корзину</button></article>`}
function renderGrid(sel,products,empty){const box=$(sel);if(!box)return;const limit=Number(box.dataset.limit||5);const list=products.filter(p=>stock(p)>0).slice(0,limit);box.innerHTML=list.length?list.map(card).join(''):`<div class="notice">${empty}</div>`;bindProductButtons(box)}
function bindProductButtons(scope=document){scope.querySelectorAll('[data-cart]').forEach(b=>b.onclick=e=>{e.preventDefault();cart.push(b.dataset.cart);saveCart();b.textContent='✓ Добавлено';setTimeout(()=>b.textContent='В корзину',900)});scope.querySelectorAll('[data-fav]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const id=b.dataset.fav;favs=favs.includes(id)?favs.filter(x=>x!==id):[...favs,id];b.classList.toggle('active',favs.includes(id));saveFav()})}
async function renderCatalogMenu(){let cats=[];try{cats=await loadCollection(COLLECTIONS.categories)}catch(e){}cats.sort((a,b)=>Number(a.order??999)-Number(b.order??999)||String(a.title||a.name||'').localeCompare(String(b.title||b.name||''),'ru'));const pb=$('#catalogParents'),cb=$('#catalogChildren'),tb=$('#megaTitle');if(!pb||!cb||!tb)return;const parents=cats.filter(c=>!c.parentId),children=cats.filter(c=>c.parentId);const name=c=>c.title||c.name||'Без названия';function render(parent){const list=children.filter(c=>c.parentId===parent.id||c.parentId===parent.externalId);tb.textContent=name(parent);cb.innerHTML=(list.length?list:[parent]).map(ch=>`<a href="catalog.html?category=${encodeURIComponent(name(ch))}" class="mega-child"><span>${ch.icon||'AS'}</span><div><b>${list.length?name(ch):'Все товары категории'}</b><small>${name(ch)}</small></div></a>`).join('')}pb.innerHTML=parents.length?parents.map((p,i)=>`<button class="mega-parent ${i?'':'active'}" data-parent="${p.id}" type="button"><span>${p.icon||'AS'}</span>${name(p)}</button>`).join(''):'<p class="muted">Категорий пока нет</p>';if(parents[0])render(parents[0]);$$('.mega-parent').forEach(btn=>btn.onmouseenter=btn.onclick=()=>{ $$('.mega-parent').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const p=parents.find(x=>x.id===btn.dataset.parent);if(p)render(p)})}
async function getHomeBlockOrder(){try{const snap=await getDoc(doc(db,COLLECTIONS.settings,'homeBlocks'));return snap.exists()?snap.data():{}}catch(e){return {}}}
function applyHomeBlockOrder(order){const map={bestsellers:'#bestsellers',new:'#newProducts',hot:'#productsBlock',recentlyViewed:'#recentlyViewed'};Object.entries(map).forEach(([key,sel])=>{const el=$(sel);if(el)el.style.order=Number(order[key]??999)})}
async function renderHome(){let products=await loadCollection(COLLECTIONS.products);const blockOrder=await getHomeBlockOrder();applyHomeBlockOrder(blockOrder);allProducts=products;let banners=[];try{banners=await loadCollection(COLLECTIONS.banners)}catch(e){}const hero=$('#hero');if(hero){const b=banners[0]||{};hero.innerHTML=`<div class="hero-content"><span class="hero-label">AUTO STYLE MARKET</span><h1>${b.title||'Автотовары для стиля, комфорта и защиты'}</h1><p>${b.text||'Подбери аксессуары, автохимию и полезные товары для своего автомобиля в пару кликов.'}</p><div class="hero-actions"><a href="catalog.html" class="primary hero-btn">Смотреть каталог</a><a href="#bestsellers" class="hero-link">Лидеры продаж</a></div></div><div class="hero-visual"><div class="hero-car">AUTO</div></div>`}const bannersBox=$('#banners');if(bannersBox){const defs=[{title:'Акции',text:'Лучшие предложения недели'},{title:'Новинки',text:'Свежие товары для твоего авто'},{title:'Топ товары',text:'Популярный выбор покупателей'}];const list=banners.slice(1,4).length?banners.slice(1,4):defs;bannersBox.innerHTML=list.map(b=>`<a class="mini-banner" href="${b.link||'#productsBlock'}"><h3>${b.title}</h3><p class="muted">${b.text||''}</p></a>`).join('')}renderGrid('#newProductsGrid',products.filter(p=>isHome(p,'new')),'В админке отметьте товары: показывать на главной + блок “Новинки”.');renderGrid('#bestsellersGrid',products.filter(p=>isHome(p,'bestsellers')),'В админке отметьте товары: показывать на главной + блок “Лидеры продаж”.');renderGrid('#productsGrid',products.filter(p=>isHome(p,'hot')),'В админке отметьте товары для главной.');await renderRecentlyViewed(products);saveCart()}
async function renderRecentlyViewed(products){const ids=JSON.parse(localStorage.getItem('viewedProducts')||'[]');const byId=new Map(products.map(p=>[p.id,p]));let list=ids.map(id=>byId.get(id)).filter(Boolean);if(!list.length){$('#recentlyViewed')&&($('#recentlyViewed').style.display='none');return}renderGrid('#recentlyViewedGrid',list,'Вы пока не смотрели товары.')}
function setupExpand(){document.addEventListener('click',e=>{const b=e.target.closest('[data-expand]');if(!b)return;const grid=document.getElementById(b.dataset.expand);if(!grid)return;grid.dataset.limit= grid.dataset.limit==='999'?'5':'999';b.textContent=grid.dataset.limit==='999'?'Свернуть':'Смотреть все';renderHome().then(()=>document.getElementById(b.dataset.expand)?.scrollIntoView({behavior:'smooth',block:'start'}))})}
function setupSearch(){const input=$('#homeSearch')||$('#siteSearch'),btn=$('#homeSearchBtn')||$('#siteSearchBtn');const go=()=>{const q=encodeURIComponent((input?.value||'').trim());location.href=q?`catalog.html?search=${q}`:'catalog.html'};btn&&(btn.onclick=go);input&&input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();go()}})}
function authModal(){const modal=$('#authModal');if(!modal)return;$('#openAuth')&&($('#openAuth').onclick=()=>modal.classList.add('open'));$('#closeAuth')&&($('#closeAuth').onclick=()=>modal.classList.remove('open'));$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#loginForm').style.display=t.dataset.tab==='login'?'block':'none';$('#registerForm').style.display=t.dataset.tab==='register'?'block':'none'});$('#loginForm')&&($('#loginForm').onsubmit=async e=>{e.preventDefault();await signInWithEmailAndPassword(auth,$('#loginEmail').value.trim(),$('#loginPass').value);modal.classList.remove('open')});$('#registerForm')&&($('#registerForm').onsubmit=async e=>{e.preventDefault();const res=await createUserWithEmailAndPassword(auth,$('#regEmail').value.trim(),$('#regPass').value);await setDoc(doc(db,COLLECTIONS.users,res.user.uid),{name:$('#regName').value.trim(),email:$('#regEmail').value.trim(),role:'user',createdAt:new Date().toISOString()});await sendEmailVerification(res.user);alert('Аккаунт создан. Проверьте письмо на почте.');modal.classList.remove('open')});onAuthStateChanged(auth,u=>{const authBtn=$('#openAuth'),dd=$('#accountDrop');if(u){authBtn&&(authBtn.style.display='none');if(dd){dd.style.display='block';$('#userEmail')&&($('#userEmail').textContent=u.email);$('#logout')&&($('#logout').onclick=()=>signOut(auth))}}else{authBtn&&(authBtn.style.display='inline-block');dd&&(dd.style.display='none')}});$('#accountBtn')&&($('#accountBtn').onclick=()=>$('#accountDrop').classList.toggle('open'))}
authModal();setupSearch();setupExpand();renderHome();renderCatalogMenu();
