import { auth, db, COLLECTIONS } from './firebase.js';
import { onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut, sendEmailVerification } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { collection, getDocs, setDoc, doc } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
let cart=JSON.parse(localStorage.getItem('cart')||'[]'); let allProducts=[];
const money=v=>`${Number(v||0).toLocaleString('ru-RU')} ₽`;
const title=p=>p.title||p.name||'Без названия'; const image=p=>p.image||p.imageUrl||p.photo||''; const stock=p=>Number(p.stock??p.quantity??p.count??0);
function oldPrice(p){return Number(p.oldPrice||p.old_price||p.priceOld||p.compareAtPrice||p.priceBefore||0)}
function discount(p){let d=Number(p.discount||p.discountPercent||p.sale||0); if(!d && oldPrice(p)>Number(p.price||0)) d=Math.round((oldPrice(p)-Number(p.price||0))/oldPrice(p)*100); return d>0?d:0}
function updateCart(){localStorage.setItem('cart',JSON.stringify(cart)); const c=$('#cartCount'); if(c)c.textContent=cart.length}
async function getCol(name){const snap=await getDocs(collection(db,name)); return snap.docs.map(d=>({id:d.id,...d.data()}))}
function card(p, withCart=false){const d=discount(p), op=oldPrice(p); return `<a class="modern-card" href="product.html?id=${p.id}">${d?`<span class="discount-badge">-${d}%</span>`:''}<span class="fav-heart">♡</span><div class="modern-card-image">${image(p)?`<img src="${image(p)}" alt="${title(p)}">`:'Фото'}</div><h3 class="modern-card-title">${title(p)}</h3><div class="modern-code">${p.code?`Код: ${p.code}`:''}</div><div class="modern-price"><b>${money(p.price)}</b>${op?`<span class="old-price">${money(op)}</span>`:''}</div>${withCart?`<button class="black-cart" data-id="${p.id}" type="button">🛒 В корзину</button>`:''}</a>`}
function renderProducts(){let visible=allProducts.filter(p=>stock(p)>0 && (p.showOnHome===true || p.showOnHome===undefined)).slice(0,5); const hot=$('#productsGrid'); if(hot) hot.innerHTML=visible.length?visible.map(p=>card(p)).join(''):'<div class="notice">Товары не найдены.</div>'; const ng=$('#newProductsGrid'); if(ng){let newest=allProducts.filter(p=>stock(p)>0).slice(5,10); if(!newest.length)newest=visible; ng.innerHTML=newest.map(p=>card(p)).join('')}}
async function renderCatalogMenu(){let categories=[]; try{categories=await getCol(COLLECTIONS.categories)}catch(e){} const parentsBox=$('#catalogParents'), childrenBox=$('#catalogChildren'), titleBox=$('#megaTitle'); if(!parentsBox||!childrenBox||!titleBox)return; const parents=categories.filter(c=>!c.parentId), children=categories.filter(c=>c.parentId); const name=c=>c.title||c.name||'Без названия'; function renderChildren(parent){const list=children.filter(c=>c.parentId===parent.id||c.parentId===parent.externalId); titleBox.textContent=name(parent); childrenBox.innerHTML=(list.length?list:[parent]).map(ch=>`<a href="catalog.html?category=${encodeURIComponent(name(ch))}" class="mega-child"><span>${ch.icon||'AS'}</span><div><b>${name(ch)}</b><small>Смотреть товары</small></div></a>`).join('')} parentsBox.innerHTML=parents.length?parents.map((p,i)=>`<button class="mega-parent ${i?'':'active'}" data-parent="${p.id}" type="button"><span>${p.icon||'AS'}</span>${name(p)}</button>`).join(''):'<p class="muted">Категорий пока нет</p>'; if(parents[0])renderChildren(parents[0]); $$('.mega-parent').forEach(btn=>btn.onmouseenter=()=>{ $$('.mega-parent').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); const p=parents.find(x=>x.id===btn.dataset.parent); if(p)renderChildren(p)})}
function setupSearch(){const input=$('#homeSearch'),btn=$('#homeSearchBtn'); const go=()=>{const q=encodeURIComponent((input?.value||'').trim()); location.href=q?`catalog.html?search=${q}`:'catalog.html'}; if(btn)btn.onclick=go; if(input)input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();go()}}}
function authModal(){const modal=$('#authModal'); if(!modal)return; $('#openAuth')&&($('#openAuth').onclick=()=>modal.classList.add('open')); $('#closeAuth')&&($('#closeAuth').onclick=()=>modal.classList.remove('open')); $$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#loginForm').style.display=t.dataset.tab==='login'?'block':'none';$('#registerForm').style.display=t.dataset.tab==='register'?'block':'none'}); $('#loginForm')&&($('#loginForm').onsubmit=async e=>{e.preventDefault();await signInWithEmailAndPassword(auth,$('#loginEmail').value.trim(),$('#loginPass').value);modal.classList.remove('open')}); $('#registerForm')&&($('#registerForm').onsubmit=async e=>{e.preventDefault();const res=await createUserWithEmailAndPassword(auth,$('#regEmail').value.trim(),$('#regPass').value);await setDoc(doc(db,COLLECTIONS.users,res.user.uid),{name:$('#regName').value.trim(),email:$('#regEmail').value.trim(),role:'user',createdAt:new Date().toISOString()});await sendEmailVerification(res.user);alert('Аккаунт создан. Проверьте почту.');modal.classList.remove('open')}); onAuthStateChanged(auth,u=>{const open=$('#openAuth'),dd=$('#accountDrop'); if(u){if(open)open.style.display='none'; if(dd){dd.style.display='block'; $('#userEmail')&&($('#userEmail').textContent=u.email||'Аккаунт'); $('#logout')&&($('#logout').onclick=()=>signOut(auth))}}else{if(open)open.style.display='inline-flex'; if(dd)dd.style.display='none'}}); $('#accountBtn')&&($('#accountBtn').onclick=e=>{e.preventDefault();$('#accountDrop').classList.toggle('open')})}
async function init(){authModal(); setupSearch(); updateCart(); try{allProducts=await getCol(COLLECTIONS.products)}catch(e){allProducts=[]} renderProducts(); renderCatalogMenu()} init();
