import { auth, db, COLLECTIONS } from './firebase.js';
import { onAuthStateChanged, signOut, signInWithEmailAndPassword, createUserWithEmailAndPassword, sendEmailVerification } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { collection, getDocs, setDoc, doc } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s); const fmt=new Intl.NumberFormat('ru-RU');
let items=[],categories=[],cart=JSON.parse(localStorage.getItem('cart')||'[]'),favorites=JSON.parse(localStorage.getItem('favorites')||'[]'),page=1; const perPage=6;
const grid=$('#catalogGrid'), loader=$('#catalogLoader');
const money=v=>`${Number(v||0).toLocaleString('ru-RU')} ₽`; const title=p=>p.title||p.name||'Товар'; const image=p=>p.image||p.imageUrl||p.photo||''; const stock=p=>Number(p.stock??p.quantity??p.count??0); const group=p=>p.group||p.category||p.categoryName||p.tag||'Без группы';
function oldPrice(p){return Number(p.oldPrice||p.old_price||p.priceOld||p.compareAtPrice||p.priceBefore||0)} function discount(p){let d=Number(p.discount||p.discountPercent||p.sale||0); if(!d && oldPrice(p)>Number(p.price||0)) d=Math.round((oldPrice(p)-Number(p.price||0))/oldPrice(p)*100); return d>0?d:0}
function updateCart(){localStorage.setItem('cart',JSON.stringify(cart)); const c=$('#cartCount'); if(c)c.textContent=cart.length}
function saveFav(){localStorage.setItem('favorites',JSON.stringify(favorites));}
function toggleFavorite(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];saveFav();document.querySelectorAll(`[data-fav=\"${id}\"]`).forEach(btn=>btn.classList.toggle('active',favorites.includes(id)));}
async function getCol(name){const snap=await getDocs(collection(db,name)); return snap.docs.map(d=>({id:d.id,...d.data()}))}
function card(p){const d=discount(p),op=oldPrice(p),fav=favorites.includes(p.id);return `<article class="modern-card">${d?`<span class="discount-badge">-${d}%</span>`:''}<button class="fav-heart ${fav?'active':''}" data-fav="${p.id}" type="button" aria-label="В избранное">♡</button><a href="product.html?id=${p.id}" class="modern-card-link"><div class="modern-card-image">${image(p)?`<img src="${image(p)}" alt="${title(p)}">`:'Фото'}</div><h3 class="modern-card-title">${title(p)}</h3><div class="modern-cat">Группа: ${group(p)}</div><div class="modern-price"><b>${money(p.price)}</b>${op?`<span class="old-price">${money(op)}</span>`:''}</div><div class="stock-green">${stock(p)>0?`В наличии: ${stock(p)} шт.`:'Нет в наличии'}</div></a><button class="black-cart" data-id="${p.id}" type="button">🛒 В корзину</button></article>`}
function filtered(){const q=($('#search')?.value||'').toLowerCase(), c=$('#category')?.value||'', pf=Number($('#priceFrom')?.value||0), pt=Number($('#priceTo')?.value||999999999), disc=$('#discountOnly')?.checked; let list=items.filter(p=>{const text=`${p.code||''} ${p.article||''} ${title(p)} ${p.description||''} ${p.category||''}`.toLowerCase(); if(c && p.category!==c)return false; if(q && !text.includes(q))return false; if(Number(p.price||0)<pf || Number(p.price||0)>pt)return false; if(disc && !discount(p))return false; if(stock(p)<=0)return false; return true}); const s=$('#sortTop')?.value||$('#sort')?.value||''; if(s==='priceAsc')list.sort((a,b)=>Number(a.price||0)-Number(b.price||0)); if(s==='priceDesc')list.sort((a,b)=>Number(b.price||0)-Number(a.price||0)); if(s==='nameAsc')list.sort((a,b)=>title(a).localeCompare(title(b),'ru')); return list}
function render(){if(!grid)return; const list=filtered(); const pages=Math.max(1,Math.ceil(list.length/perPage)); if(page>pages)page=pages; const chunk=list.slice((page-1)*perPage,page*perPage); $('#catalogCount')&&($('#catalogCount').textContent=`${list.length} товаров`); $('#foundText')&&($('#foundText').textContent=`Найдено: ${list.length} товаров`); grid.innerHTML=chunk.length?chunk.map(card).join(''):'<div class="notice">Товары не найдены.</div>'; const pag=$('#pagination'); if(pag)pag.innerHTML=Array.from({length:pages},(_,i)=>`<button class="${i+1===page?'active':''}" data-page="${i+1}" type="button">${i+1}</button>`).slice(0,7).join(''); $$('[data-page]').forEach(b=>b.onclick=()=>{page=Number(b.dataset.page); render(); scrollTo({top:0,behavior:'smooth'})}); $$('[data-id]').forEach(b=>b.onclick=e=>{e.preventDefault(); cart.push(b.dataset.id); updateCart(); b.textContent='Добавлено'; setTimeout(()=>b.textContent='🛒 В корзину',900)}); $$('.fav-heart').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();toggleFavorite(b.dataset.fav)})}
async function renderCatalogMenu(){const parentsBox=$('#catalogParents'), childrenBox=$('#catalogChildren'), titleBox=$('#megaTitle'); if(!parentsBox||!childrenBox||!titleBox)return; const parents=categories.filter(c=>!c.parentId),children=categories.filter(c=>c.parentId); const name=c=>c.title||c.name||'Без названия'; function show(parent){const list=children.filter(c=>c.parentId===parent.id||c.parentId===parent.externalId); titleBox.textContent=name(parent); childrenBox.innerHTML=(list.length?list:[parent]).map(ch=>`<a href="catalog.html?category=${encodeURIComponent(name(ch))}" class="mega-child"><span>${ch.icon||'AS'}</span><div><b>${name(ch)}</b><small>Смотреть товары</small></div></a>`).join('')} parentsBox.innerHTML=parents.length?parents.map((p,i)=>`<button class="mega-parent ${i?'':'active'}" data-parent="${p.id}" type="button"><span>${p.icon||'AS'}</span>${name(p)}</button>`).join(''):'<p class="muted">Категорий пока нет</p>'; if(parents[0])show(parents[0]); $$('.mega-parent').forEach(btn=>btn.onmouseenter=()=>{ $$('.mega-parent').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); const p=parents.find(x=>x.id===btn.dataset.parent); if(p)show(p)})}
function setupAuth(){const modal=$('#authModal'); $('#openAuth')&&($('#openAuth').onclick=()=>modal.classList.add('open')); $('#closeAuth')&&($('#closeAuth').onclick=()=>modal.classList.remove('open')); $$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#loginForm').style.display=t.dataset.tab==='login'?'block':'none';$('#registerForm').style.display=t.dataset.tab==='register'?'block':'none'}); $('#loginForm')&&($('#loginForm').onsubmit=async e=>{e.preventDefault();await signInWithEmailAndPassword(auth,$('#loginEmail').value.trim(),$('#loginPass').value);modal.classList.remove('open')}); $('#registerForm')&&($('#registerForm').onsubmit=async e=>{e.preventDefault();const res=await createUserWithEmailAndPassword(auth,$('#regEmail').value.trim(),$('#regPass').value);await setDoc(doc(db,COLLECTIONS.users,res.user.uid),{name:$('#regName').value.trim(),email:$('#regEmail').value.trim(),role:'user',createdAt:new Date().toISOString()});await sendEmailVerification(res.user);alert('Аккаунт создан. Проверьте почту.');modal.classList.remove('open')}); onAuthStateChanged(auth,u=>{const open=$('#openAuth'),dd=$('#accountDrop'); if(u){if(open)open.style.display='none'; if(dd){dd.style.display='block'; $('#userEmail')&&($('#userEmail').textContent=u.email||'Аккаунт'); $('#logout')&&($('#logout').onclick=()=>signOut(auth))}}else{if(open)open.style.display='inline-flex'; if(dd)dd.style.display='none'}}); $('#accountBtn')&&($('#accountBtn').onclick=e=>{e.preventDefault();$('#accountDrop').classList.toggle('open')})}
function events(){['search','category','sort','sortTop','priceFrom','priceTo','discountOnly'].forEach(id=>{const el=$('#'+id); if(el)el.addEventListener(id==='search'?'input':'change',()=>{page=1;render()})}); $('#applyFilters')&&($('#applyFilters').onclick=()=>{page=1;render()}); $('#resetFilters')&&($('#resetFilters').onclick=()=>{['search','priceFrom','priceTo'].forEach(id=>{const el=$('#'+id); if(el)el.value=''}); $('#category').value=''; $('#sort').value=''; $('#sortTop').value=''; $('#discountOnly').checked=false; page=1;render()}); $('#cartBtn')&&($('#cartBtn').onclick=()=>location.href='cart.html'); $('#favBtn')&&($('#favBtn').onclick=()=>alert('Избранное скоро будет доступно.')); const top=$('#topSearch'),btn=$('#topSearchBtn'); const go=()=>{const q=(top?.value||'').trim(); if($('#search')){$('#search').value=q;page=1;render()}}; btn&&(btn.onclick=go); top&&(top.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();go()}})}
async function init(){setupAuth(); events(); updateCart(); loader&&loader.classList.add('show'); try{items=await getCol(COLLECTIONS.products); categories=await getCol(COLLECTIONS.categories)}catch(e){items=[];categories=[]} const params=new URLSearchParams(location.search); if(params.get('search')){$('#search').value=params.get('search'); $('#topSearch')&&($('#topSearch').value=params.get('search'))} if(params.get('category'))$('#category').value=params.get('category'); if($('#category'))$('#category').innerHTML='<option value="">Все категории</option>'+categories.map(c=>`<option value="${c.title||c.name||''}">${c.title||c.name||'Без названия'}</option>`).join(''); await renderCatalogMenu(); loader&&loader.classList.remove('show'); render()} init();
