import { initializeApp, getApps } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { getFirestore, doc, getDoc } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
const config={apiKey:"AIzaSyBZ-AW6XoMR14KmBtlz2q06Z0jPGXnWMTw",authDomain:"auto-style-4dbb7.firebaseapp.com",projectId:"auto-style-4dbb7",storageBucket:"auto-style-4dbb7.firebasestorage.app",messagingSenderId:"217023127803",appId:"1:217023127803:web:502ebd5d1981c8aeb0905e"};
const app=getApps()[0]||initializeApp(config),auth=getAuth(app),db=getFirestore(app);
const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();
const map={'index.html':'staffHome','beznal.html':'staffBeznal','smena.html':'staffShift','discount.html':'staffDiscount','baza.html':'staffKnowledge','close-shift.html':'staffCloseShift','cash-diff.html':'staffCashDiff','zarplata.html':'staffSalary','admin.html':'legacyAdmin','#u043f#u0440#u0435#u043c#u0438#u044f.html':'staffSalary','#u0440#u0435#u0434#u0430#u043a#u0442#u043e#u0440-#u043f#u0440#u0435#u043c#u0438#u0438.html':'legacyAdmin'};
const need=map[page]||'staffHome';
document.documentElement.style.visibility='hidden';
function deny(msg){document.documentElement.style.visibility='visible';document.body.innerHTML=`<main style="font-family:Arial;max-width:620px;margin:80px auto;padding:28px;border:1px solid #ddd;border-radius:18px"><h1>Доступ закрыт</h1><p>${msg}</p><a href="../profile.html#staff-workspace">Вернуться в профиль</a></main>`;}
onAuthStateChanged(auth,async user=>{if(!user){deny('Войдите в аккаунт на основном сайте.');return;}try{const snap=await getDoc(doc(db,'autostyle_users',user.uid));const p=snap.exists()?snap.data():{};if(p.role==='admin'||p.permissions?.[need]===true){document.documentElement.style.visibility='visible';const back=document.createElement('a');back.href='../profile.html#staff-workspace';back.textContent='← Профиль AutoStyle';back.style.cssText='position:fixed;right:18px;bottom:18px;z-index:99999;background:#111827;color:#fff;padding:11px 15px;border-radius:12px;text-decoration:none;font:600 14px Arial';document.body.appendChild(back);}else deny('Администратор не выдал доступ к этому разделу.');}catch(e){deny('Не удалось проверить права доступа.');}});
